### ISSUE TITLE
MSR Status does not update when JSOAC-E/JMOC save is made

### ISSUE THREAD

**Issue by btroop202** [chanm003/airsupport#39]

**Comment by btroop202** [comment]
As well as when the support element makes a change

**Comment by chanm003** [comment]
On JSOAC/JMOC tab, we update Status to 'Assigned' only if the the Unit Assigned dropdown has changed, correct?

What about on the Support Unit tab?  Is the idea to change the Status to 'Planning'?  If so, when?  Everytime the Support Unit clicks "Save"?
