### ISSUE TITLE
ON JSOAC / JMOC, when a unit is assigned status should update to assigned, and message should say which unit is assigned

### ISSUE THREAD

**Issue by btroop202** [chanm003/airsupport#43]

**Comment by chanm003** [comment]
![alt text](https://s23.postimg.org/k4q0tx48b/When-_Save-button-clicked-on-_JSOAC-_JMOC-tab.png)

@btroop202 
When user clicks save button, I look to see if the 'Unit Assigned' dropdown has changed.   The system sets the status of the MSR to 'Assigned' if and only if that dropdown value has changed, correct?

Are there other actions that can be taken on this tab that will trigger a status change?

**Comment by btroop202** [comment]
No that is correct, on the dashboard can you add the status, and do it as a group by

**Comment by chanm003** [comment]
@btroop202 Can you tell me more about the statuses "Assigned" and "Vetting"?  Which users of the system would set the MSR to this status?

Here is how I visualize the various ways users would interact with the tab:
[State Diagram](https://github.com/chanm003/airsupport/wiki/MSR-Status---State-Diagram)

**Comment by chanm003** [comment]
@btroop202 
On the dashboard weren't we going to go with 5 tables?
- New MSRs submitted
- MSRs awaiting vetting
- MSRs assigned to Support Units
- Current MSRs
- MSRs for next 30 days
